"""Build ../questions.js from the DE-ZH question bank Excel (all-options version).

Source: germany-permanent-residence/german-exam/question-bank/
        Einbuergerungstest_Fragenkatalog_DE-ZH_alle-Optionen.xlsx
        (BAMF Gesamtfragenkatalog, Stand 2025-05-07; 300 national + 10 Berlin questions)

Usage:  python build_questions.py path/to/Einbuergerungstest_Fragenkatalog_DE-ZH_alle-Optionen.xlsx
Needs:  openpyxl
"""

import json
import sys
from pathlib import Path

from openpyxl import load_workbook

TOPICS = {
    "Geschichte": "歷史",
    "Politik": "政治",
    "法律與基本權": "法律與基本權",
    "Staat": "國家",
    "社會與家庭": "社會與家庭",
    "Europa und Welt": "歐洲與世界",
    "Bund und Länder": "聯邦與各邦",
    "Religion und Kultur": "宗教與文化",
    "Bildung und Arbeit": "教育與工作",
    "Wirtschaft": "經濟",
    "Berlin": "柏林",
}

# Picture questions: the images are only in the official PDF, so describe the correct picture.
PICTURE_HINTS = {
    ("N", 21): "正解圖：金色盾牌上一隻黑色單頭鷹（紅嘴紅爪）＝聯邦徽章 Bundeswappen。",
    ("N", 55): "照片是國會大廈 Reichstag（玻璃圓頂）＝聯邦議院所在地。",
    ("N", 70): "照片只是背景；重點是總統「提名總理人選」。",
    ("N", 130): "有效選票：第一票（左欄）與第二票（右欄）各只畫一個叉。",
    ("N", 176): "記法：西北英、東蘇、南美、西南法 → 1 英 2 蘇 3 美 4 法。",
    ("N", 181): "照片是布蘭特在華沙猶太區紀念碑前下跪。",
    ("N", 209): "正解圖：錘子＋圓規，外圍麥穗環＝東德國徽。",
    ("N", 216): "照片是國會議場牆上的大型聯邦之鷹。",
    ("N", 226): "正解圖：藍底、12 顆金星圍成一圈。",
    ("B", 1): "正解圖：白底盾牌上一隻直立黑熊，上方有皇冠。",
    ("B", 8): "地圖上柏林是東北部、被布蘭登堡邦完全包圍的小塊。",
}

LETTERS = "ABCD"


def split(cell):
    de, _, zh = str(cell).partition("\n")
    return [de.strip(), zh.strip()]


def rows(ws, prefix):
    out = []
    for r in ws.iter_rows(min_row=2, values_only=True):
        if r[0] is None:
            continue
        n = int(r[0])
        q = {
            "id": f"{prefix}{n}",
            "set": prefix,
            "n": n,
            "topic": TOPICS[r[1]],
            "q": r[2].strip(),
            "qz": r[3].strip(),
            "o": [split(c) for c in r[4:8]],
            "a": LETTERS.index(r[8].strip()),
        }
        if r[11]:
            q["pic"] = int(r[12])
            q["hint"] = PICTURE_HINTS[(prefix, n)]
        out.append(q)
    return out


def main(src):
    wb = load_workbook(src, read_only=True)
    data = rows(wb["全國題 300"], "N") + rows(wb["柏林題 10"], "B")
    assert len(data) == 310, len(data)
    out = Path(__file__).resolve().parent.parent / "questions.js"
    body = ",\n".join(json.dumps(q, ensure_ascii=False, separators=(",", ":")) for q in data)
    out.write_text(
        "// Generated by tools/build_questions.py — BAMF Gesamtfragenkatalog (Stand 2025-05-07), DE-ZH.\n"
        f"window.QUESTIONS = [\n{body}\n];\n",
        encoding="utf-8",
    )
    print(f"wrote {out} ({len(data)} questions)")


if __name__ == "__main__":
    main(sys.argv[1])
